name: CI
on:
  - push
#   - pull_request
jobs:
  test:
    env: 
      GKS_ENCODING: "utf8"
      GKSwstype: "nul"
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.version == 'nightly' || matrix.version == '^1.10.0-0' }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1.9' #^1-0 and ^1.9-0 are not recognised
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
        arch:
          - x64
        test_env_var:
          - "estimation"
          - "higher_order"
          - "plots"
          - "basic"
        include:
          - os: ubuntu-latest
            prefix: xvfb-run
          - version: '1.8'
            os: ubuntu-latest
            arch: x64
            test_env_var: "basic"
          - version: '1.8'
            os: ubuntu-latest
            arch: x64
            test_env_var: "plots"
          - version: '^1.10.0-0'
            os: ubuntu-latest
            arch: x64
            test_env_var: "estimation"
            allow_failure: true
          - version: '^1.10.0-0'
            os: ubuntu-latest
            arch: x64
            test_env_var: "higher_order"
            allow_failure: true
          - version: '^1.10.0-0'
            os: ubuntu-latest
            arch: x64
            test_env_var: "plots"
            allow_failure: true
          - version: '^1.10.0-0'
            os: ubuntu-latest
            arch: x64
            test_env_var: "basic"
            allow_failure: true
          - version: 'nightly'
            os: ubuntu-latest
            arch: x64
            test_env_var: "basic"
            allow_failure: true
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - name: Set Custom Test Environment Variable
        run: echo "TEST_ENV_VAR=${{ matrix.test_env_var }}" >> $GITHUB_ENV
      - name: Set JULIA_NUM_THREADS for Julia 1.9 on Ubuntu
        if: matrix.version == '1.9' && matrix.os == 'ubuntu-latest'
        run: echo "JULIA_NUM_THREADS=2" >> $GITHUB_ENV
      - uses: actions/cache@v3
        env:
          cache-name: cache-artifacts
        with:
          path: ~/.julia/artifacts
          key: ${{ runner.os }}-test-${{ env.cache-name }}-${{ hashFiles('**/Project.toml') }}
          restore-keys: |
            ${{ runner.os }}-test-${{ env.cache-name }}-
            ${{ runner.os }}-test-
            ${{ runner.os }}-
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
        with:
          prefix: ${{ matrix.prefix }}  # for `xvfb-run`
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: lcov.info
